const bcrypt = require('bcrypt');
const saltRounds = 10;
export const hashPassword = async (plainPassword: string) => {
  try {
    const h = await bcrypt.hash(plainPassword, saltRounds);
    return h;
  } catch (error) {
    console.error(error);
  }
};

export const comparePassword = async (
  plainPassword: string,
  hashPass: string,
) => {
  try {
    return await bcrypt.compare(plainPassword, hashPass);
  } catch (error) {
    console.error(error);
  }
};

export function removeVietnameseTones(str: string): string {
  const map = {
    à: 'a',
    á: 'a',
    â: 'a',
    ả: 'a',
    ã: 'a',
    ạ: 'a',
    ầ: 'a',
    ấ: 'a',
    ậ: 'a',
    ẫ: 'a',
    ẩ: 'a',
    ă: 'a',
    ẳ: 'a',
    ẵ: 'a',
    ặ: 'a',
    ắ: 'a',
    ằ: 'a',
    À: 'a',
    Á: 'a',
    Â: 'a',
    Ả: 'a',
    Ã: 'a',
    Ạ: 'a',
    Ầ: 'a',
    Ấ: 'a',
    Ậ: 'a',
    Ẫ: 'a',
    Ẩ: 'a',
    Ă: 'a',
    Ằ: 'a',
    Ắ: 'a',
    Ẵ: 'a',
    Ặ: 'a',
    Ẳ: 'a',
    è: 'e',
    é: 'e',
    ẻ: 'e',
    ẽ: 'e',
    ê: 'e',
    ể: 'e',
    ễ: 'e',
    ế: 'e',
    ề: 'e',
    ệ: 'e',
    ẹ: 'e',
    È: 'e',
    É: 'e',
    Ẻ: 'e',
    Ẽ: 'e',
    Ê: 'e',
    Ể: 'e',
    Ễ: 'e',
    Ế: 'e',
    Ề: 'e',
    Ệ: 'e',
    Ẹ: 'e',
    ì: 'i',
    í: 'i',
    ỉ: 'i',
    ĩ: 'i',
    ị: 'i',
    Ì: 'i',
    Í: 'i',
    Ỉ: 'i',
    Ĩ: 'i',
    Ị: 'i',
    ò: 'o',
    ô: 'o',
    ổ: 'o',
    ộ: 'o',
    ồ: 'o',
    ố: 'o',
    ỗ: 'o',
    ó: 'o',
    ỏ: 'o',
    õ: 'o',
    ọ: 'o',
    Ò: 'o',
    Ô: 'o',
    Ổ: 'o',
    Ộ: 'o',
    Ồ: 'o',
    Ố: 'o',
    Ỗ: 'o',
    Ó: 'o',
    Ỏ: 'o',
    Õ: 'o',
    Ọ: 'o',
    ù: 'u',
    ú: 'u',
    ủ: 'u',
    ũ: 'u',
    ư: 'u',
    ừ: 'u',
    ứ: 'u',
    ự: 'u',
    ử: 'u',
    ữ: 'u',
    ụ: 'u',
    Ù: 'u',
    Ú: 'u',
    Ủ: 'u',
    Ũ: 'u',
    Ư: 'u',
    Ừ: 'u',
    Ứ: 'u',
    Ự: 'u',
    Ử: 'u',
    Ữ: 'u',
    Ụ: 'u',
    ỳ: 'y',
    ý: 'y',
    ỷ: 'y',
    ỹ: 'y',
    ỵ: 'y',
    Ỳ: 'y',
    Ý: 'y',
    Ỷ: 'y',
    Ỹ: 'y',
    Ỵ: 'y',
    đ: 'd',
    Đ: 'd',
  };
  return str.replace(
    /[àáảâắằặẵẳẩẫậầấãạèéẻẽêếềễệẹìíỉĩịòóỏơõôồốỗổộọùúưừứữửựủũụỳýỷỹỵđÒÔỔỘỒỐỖÓỎÕỌÙÚỦŨƯỪỨỰỬỮỤỲÝỶỸỴĐÀÁÂẢÃẠẦẤẬẪẨĂẰẮẴẶẲÈÉẺẼÊỂỄẾỀỆẸ]/g,
    (match) => map[match],
  );
}

export function generateRandomNumericId(): string {
  return Math.floor(Math.random() * 10000000000).toString();
}
